#!/bin/sh
ss_header="\\n----\\n"


output=$(\
printf "%b" "Machine Stats${ss_header}" ;\
printf "\\n%b" "IP Info${ss_header}" ;\
_showIP ;\
printf "\\n%b" "Battery Info${ss_header}" ;\
_showBattery)


case "${@}" in
    *--cow*)
        if [ "$(command -v cowsay)" ]; then 
            printf '%b\n\n' "${output}" | cowsay -n
            exit 0
        fi
    ;;
esac


printf '%b\n\n' "${output}" 

