#!/bin/sh
ssc_green=$(tput setaf 2)
ssc_blue=$(tput setaf 4)
ssc_reset=$(tput sgr0)
ssc_bold=$(tput bold)
ss_header="\\n----\\n"


output=$(\
printf "%b" "Machine Stats${ss_header}" ;\
printf "\\n%b" "IP Info${ss_header}" ;\
#printf "%s\\n" '----' ;\
_showIP ;\
printf "\\n%b" "Battery Info${ss_header}" ;\
_showBattery)


case "${@}" in
    *--cow*)
        if [ "$(command -v cowsay)" ]; then 
            printf '%b\n\n' "${output}" | cowsay -n | \
                sed -re 's/^\|  ([[:digit:].]+)\/([[:digit:]]+)/|  '"${ssc_green}${ssc_bold}\\1${ssc_reset}\\/${ssc_blue}${ssc_bold}\\2${ssc_reset}/" \
                    -e  's/(Connected To: )([[:alnum:] [:punct:]]+)\|/\1'"${ssc_green}${ssc_bold}\\2${ssc_reset}"'|/' \
                    -e '/^\| [[:space:]](state|time to empty|percentage|capacity|time to full):/{s/:([[:space:]]+[[:alnum:]][[:alnum:][:punct:][:space:]]+[^|])/:'"${ssc_green}${ssc_bold}\\1${ssc_reset}"'/}' 
            exit 0
        fi
    ;;
esac


printf '%b\n\n' "${output}" | sed -re 's/^ ([[:digit:].]+)\/([[:digit:]]+)/ '"${ssc_green}${ssc_bold}\\1${ssc_reset}\\/${ssc_blue}${ssc_bold}\\2${ssc_reset}/" \
                                   -e 's/(Connected To: )([[:alnum:] [:punct:]]+)/\1'"${ssc_green}${ssc_bold}\\2${ssc_reset}"'/' \
                                   -e '/^[[:space:]](state|time to empty|percentage|capacity|time to full):/{s/:([[:space:]]+[[:alnum:]][[:alnum:][:punct:][:space:]]+)/:'"${ssc_green}${ssc_bold}\\1${ssc_reset}"'/}'

#_showIP | sed -re 's/^ ([[:digit:].]+)\/([[:digit:]]+)/ '"${ssc_green}${ssc_bold}\\1${ssc_reset}\\/${ssc_blue}${ssc_bold}\\2${ssc_reset}/" ;\
