#!/bin/sh

nmcli connection show -s \
    "$(nmcli connection show --active \
        | grep -v 'NAME\s\+UUID.*' \
        | sed -e 's/\(.\+\)\s\s\+[a-f0-9-]\{36\}.*/\1/')" \
    | grep 'psk:' \
    | awk '{ print $2 }' \
    | cowsay
