#!/bin/sh
if [ $(which nmcli) ]; then
    coninfo=$(nmcli connection show --active | grep -vE "NAME\s+UUID" | sed -E 's/(.+)? [a-f0-9-]+ .+/\1/')
    if [ ! -z "${coninfo}" ]; then
        printf "Connected To: %b\n----\n" "${coninfo}"
    fi
else
    printf "%s\n" "The nmcli binary was not found in path"
    printf "%s\n----\n" "Connection info is not available"
fi
ip -4 addr | grep -oE "(inet [0-9./]+)|([0-9]+: [0-9a-zA-Z]+:)" | \
sed -r -e 's/^[[:digit:]]+: ([[:alpha:][:digit:]]+):/\1/' \
       -e 's/^inet (.+)/ \1 \n/' | \
sed -e '${/^$/d}'

