#!/bin/sh

if [ ! "$(command -v whois)" ]; then
    printf '\nNeed to install whois to use.\n\n'
    exit 1
fi

if [ "${1}" = "-h" ] || ([ -z "${1}" ] || [ -z "${2}" ] || [ ! -f "${2}" ]); then
    printf '\n%s\n %s\n %s\n' "Script expects 2 arguments" \
        " 1: Domain" \
        " 2: Reference Whois File"
    printf '\n%s\n %s\n\n' "Vars (Behavior based on set or unset):" \
        " NOLASTRUN - Do not output lastrun.res if set"
    exit 1
fi

whoisRes="$(whois "${1}")"

# diffCount="$(printf '%s\n' "${whoisRes}" | diff -U -0 "${2}" - | grep -v ^@ | tail -n +3 | wc -l)"
diffCount="$(printf '%s\n' "${whoisRes}" | diff -y --suppress-common-lines "${2}" - | wc -l)"
if [ "${diffCount}" -eq 0 ]; then
    printf '\nSame as reference.\n\n'
elif [ "${diffCount}" -eq 2 ]; then
    printf '\nMinor Difference To Reference: Likely Only Date Changed\n\n';
else
    printf '\nDifferent: More than date changed.\n  There were %d differences.\n\n' "${diffCount}"
fi

# if [ -z ${NOLASTRUN+x} ]; then #Should be "x" IF NOLASTRUN is set, null if unset
if [ "${NOLASTRUN}" = "1" ]; then
    echo "${whoisRes}" > "${PWD}/lastrun.res"
fi
