#!/bin/sh

self="$(basename "${0}")"
outDir="${OUTDIR:-$PWD}"; outDir="${outDir%/}"
optMode=0
optCygmode=0
optWebImg=0
inArtist=''
inTitle=''
inSongFile=''
inImageFile=''
inOutputFile=''

printHelp(){
    printf '%s\n\n' "
${self}

Usage:
    ${self} [options] <artist> <title> <song file> [output filename]
    ${self} [options] i <artist> <title> <song file> <image file> [output filename]
    ${self} [options] a <song file> <image file>
    ${self} -h | --help

Notes:
    <image file> can be a local path, or a URL.
    (If using a URL, wget must be present)

Modes:
    i            Include Album Art
    a            Add Album Art To Existing File
                  (Replaces the input file)

Options:
    --cygmode    Cygwin + Non-Cygwin ffmpeg Compatibility
    -h --help    Show This Screen"

}

# Switches that need to happen first to affect how the script behaves
#  in subsequent sections.  These either cause the script to exit or
#  change how it functions such that it would be a pain to do within
#  the same loop as the main checks. 

while [ -n "${1}" ]; do
    case "${1}" in
        "-h"|"--help")
            printHelp
            exit 0 # Asked for help, so no error
            ;;
        "--cygmode")
            shift
            optCygmode=1
            ;;
        *)
            break
            ;;
    esac
done

# Options that can be combined

# while [ -n "${1}" ]; do
#     case "${1}" in
#         "--")
#             shift
#             break
#             ;;
#         "-"*)
#             while IFS= read -r line
#             do
#                 # Case statement for handling options would go here
#             done <<EOF
# $(printf '%s' "${1#-}" | sed -e 's/\(.\)/\1\n/g')
# EOF
#             shift
#             ;;
#         *)
#             break
#             ;;
#     esac
# done

if [ -n "${1}" ]; then
    case "${1}" in
        "i")
            shift
            optMode=1
            inArtist="${1}"
            inTitle="${2}"
            inSongFile="${3}"
            inImageFile="${4}"
            if [ -z "${5}" ]; then
                inOutputFile="${outDir}/${1} - ${2}.mp3"
            else
                inOutputFile="${outDir}/${5}"
            fi
            ;;
        "a")
            shift
            optMode=2
            inSongFile="${1}"
            inImageFile="${2}"
            ;;
        *)
            optMode=0
            inArtist="${1}"
            inTitle="${2}"
            inSongFile="${3}"
            if [ -z "${4}" ]; then
                inOutputFile="${outDir}/${1} - ${2}.mp3"
            else
                inOutputFile="${outDir}/${4}"
            fi
            ;;
    esac
fi

case "${inImageFile}" in
    "http://"*)
        optWebImg=1
        ;;
    "https://"*)
        optWebImg=1
        ;;
    *)
        ;;
esac

if [ ${optCygmode} -eq 1 ]; then
    inOutputFile=$(printf '%s' "${inOutputFile}" | sed -e 's#/cygdrive/\([a-zA-Z]\)/#\1:/#')
fi

errorState=0
case ${optMode} in
    0)
        if \
            [   -z "${inArtist}"     ] || \
            [   -z "${inTitle}"      ] || \
            [ ! -f "${inSongFile}"   ] || \
            [   -f "${inOutputFile}" ]; then
            errorState=1
        fi
    ;;
    1)
        if \
            [   -z "${inArtist}"      ] || \
            [   -z "${inTitle}"       ] || \
            [ ! -f "${inSongFile}"    ] || \
            [ ! -f "${inImageFile}"   ] || \
            [   -f "${inOutputFile}"  ]; then
            errorState=1
        fi
        ;;
    2)
        if \
            [ ! -f "${inSongFile}"    ] || \
            ( [ ! -f "${inImageFile}"   ] && [ ! ${optWebImg} -eq 1 ] ); then
            errorState=1
        fi
        ;;
    *)
        printf 'Fatal Error: Unhandled Mode\n\n'
        exit 1
        ;;
esac

if [ ${errorState} -eq 1 ]; then
    printf '\nSanity Check Failure\n\n'
    printHelp
    exit 1
fi

case ${optMode} in
    0)
        ffmpeg \
        -i "${inSongFile}" \
        -c:a libmp3lame \
        -ar 44100 \
        -id3v2_version 3 \
        -metadata artist="${inArtist}" \
        -metadata title="${inTitle}" \
        "${inOutputFile}"
        exit 0
        ;;
    1)
        if [ ${optWebImg} -eq 1 ]; then
            wget -q -O - "${inImageFile}" | ffmpeg \
            -i "${inSongFile}" \
            -i pipe:0 \
            -c:a libmp3lame \
            -ar 44100 \
            -id3v2_version 3 \
            -map 0 \
            -map 1 \
            -metadata artist="${inArtist}" \
            -metadata title="${inTitle}" \
            "${inOutputFile}"
        else
            ffmpeg \
            -i "${inSongFile}" \
            -i "${inImageFile}" \
            -c:a libmp3lame \
            -ar 44100 \
            -id3v2_version 3 \
            -map 0 \
            -map 1 \
            -metadata artist="${inArtist}" \
            -metadata title="${inTitle}" \
            "${inOutputFile}"
        fi
        exit 0
        ;;
    2)
        if [ ${optWebImg} -eq 1 ]; then
            if wget -q -O - "${inImageFile}" | ffmpeg \
            -i "${inSongFile}" \
            -i pipe:0 \
            -c:a copy \
            -id3v2_version 3 \
            -map_metadata 0 \
            -map 0 \
            -map 1 \
            "${inOutputFile}_tmp.mp3"; then
                inOriginalFile="${inSongFile}"
                rm "${inOriginalFile}" || \
                    ( printf 'Unable to remove original to replace'; exit 1 )
                mv "${inOutputFile}_tmp.mp3" "${inOriginalFile}" || \
                    ( printf 'Unable to rename temp file'; exit 1 )
            fi
        else
            if ffmpeg \
            -i "${inSongFile}" \
            -i "${inImageFile}" \
            -c:a copy \
            -id3v2_version 3 \
            -map_metadata 0 \
            -map 0 \
            -map 1 \
            "${inOutputFile}_tmp.mp3"; then
                inOriginalFile="${inSongFile}"
                rm "${inOriginalFile}" || \
                    ( printf 'Unable to remove original to replace'; exit 1 )
                mv "${inOutputFile}_tmp.mp3" "${inOriginalFile}" || \
                    ( printf 'Unable to rename temp file'; exit 1 )
            fi
        fi
        exit 0
        ;;
esac

printHelp
exit 1
