#!/bin/sh

self="$(basename "${0}")"
outDir="${OUTDIR:-$PWD}"; outDir="${outDir%/}"
checkSane=0
optImage=0
inArtist=''
inTitle=''
inSongFile=''
inImageFile=''
inOutputFile=''

printHelp(){
    printf '%s\n\n' "
${self}

Usage:
    ${self} <artist> <title> <song file> [output filename]
    ${self} -i <artist> <title> <song file> <image file> [output filename]
    ${self} -h | --help
    
Options:
    -i           Embed Album Art
    -h --help    Show This Screen"

}

while [ -n "${1}" ]; do
    case "${1}" in
        "-h"|"--help")
            printHelp
            exit 0 # Asked for help, so no error
            ;;
        *)
            break
    esac
done

if [ "${1}" = "-i" ]; then
    optImage=1
    shift
fi

if [ ${optImage} -eq 0 ]; then
    case $# in
        3)
            inOutputFile="${outDir}/${1} - ${2}.mp3"
            ;;
        4)
            inOutputFile="${outDir}/${4}.mp3"
            ;;
        *)
            printHelp
            exit 3
            ;;
    esac
else
    case $# in
        4)
            inOutputFile="${outDir}/${1} - ${2}.mp3"
            ;;
        5)
            inOutputFile="${outDir}/${5}.mp3"
            ;;
        *)
            printHelp
            exit 4
            ;;
    esac
    inImageFile="${4}"
fi
inArtist="${1}"
inTitle="${2}"
inSongFile="${3}"

if \
   [ -f "${inSongFile}" ]     && \
   [ ! -f "${inOutputFile}" ] && \
   ( ( [ ${optImage} -eq 1 ] && [ -f "${inImageFile}" ] ) || [ ${optImage} -eq 0 ] ); then
    checkSane=1
fi

if [ ${checkSane} -eq 1 ]; then
    if [ ${optImage} -eq 1 ]; then
        ffmpeg \
        -i "${inSongFile}" \
        -i "${inImageFile}" \
        -c:a libmp3lame \
        -ar 44100 \
        -id3v2_version 3 \
        -map 0 \
        -map 1 \
        -metadata artist="${inArtist}" \
        -metadata title="${inTitle}" \
        "${inOutputFile}"
    else
        ffmpeg \
        -i "${inSongFile}" \
        -c:a libmp3lame \
        -ar 44100 \
        -id3v2_version 3 \
        -metadata artist="${inArtist}" \
        -metadata title="${inTitle}" \
        "${inOutputFile}"
    fi
else
    printHelp
    exit 5
fi
