#!/bin/sh

tmuxan_foundTput=false

tputFunc(){
    if ${tmuxan_foundTput} ; then
        tput $@
    fi
}

if [ "${1}" = "--help" ] || [ "${1}" = "-h" ]; then
    echo " TmuxAN (Tmux [A]ttach [N]ew)" 
    echo
    echo " Requirements"
    echo "   tput"
    echo "   tmux"
    echo 
    echo " Usage: tmuxan <session name>"
    echo "   Will attach to an existing session or will"
    echo "   create a new one if the specified session does not exist."
    echo
    echo " Special Uses"
    echo "   'tmuxan ls' - List Existing Sessions"
    echo "   'tmuxan ls --force' -  Create or attach to a session named 'ls'"
    echo "   'tmuxan --help' or 'tmuxan -h' - Print this help message and exit"
    echo 
    exit 0
fi

if [ $(which tput) ]; then
    tmuxan_foundTput=true
else
    printf "%b\n\n" "Warning: Script prefers 'tput' to be present for full functionality."
fi

if [ ! $(which tmux) ]; then
    tputFunc setaf 1
    tputFunc bold
    printf "%b\n" "Error: Tmux binary is not present in path."
    printf "%b\n" "This script is a wrapper for Tmux, and is useless without it."
    tputFunc sgr0
    exit 1
fi

if [ -z ${1} ] || ([ "${1}" = "ls" ] && [ ! "${2}" = "--force" ]); then
    if [ ! "${1}" = "ls" ]; then
        tputFunc setaf 1
        tputFunc bold
        printf "%b\n" "Error: You must specify a new or existing session name."
        tputFunc sgr0
    fi
    tmux ls
else
    tmux a -t "${1}" 2>/dev/null || tmux new -s "${1}"
fi
