#!/bin/sh

tmuxan_foundTput=false

tputFunc(){
    if ${tmuxan_foundTput} ; then
        tput $@
    fi
}

if [ $(which tput) ]; then
    tmuxan_foundTput=true
else
    printf "%b\n\n" "Warning: Script prefers 'tput' to be present for full functionality."
fi

if [ ! $(which tmux) ]; then
    tputFunc setaf 1
    tputFunc bold
    printf "%b\n" "Error: Tmux binary is not present in path."
    printf "%b\n" "This script is a wrapper for Tmux, and is useless without it."
    tputFunc sgr0
    exit 1
fi

if [ -z ${1} ]; then
    tputFunc setaf 1
    tputFunc bold
    printf "%b\n" "Error: You must specify a new or existing session name."
    tputFunc sgr0
    tmux ls
else
    tmux a -t "${1}" 2>/dev/null || tmux new -s "${1}"
fi
