#!/bin/sh
twshowhelp() {
    printf '%s\n%s\n%s\n' \
        'Toggles the state of the wifi radio.' \
        ' --exec       will perform the toggle' \
        ' --status     will show the current status and exit'
}

if ! command -v nmcli 1>/dev/null 2>&1; then
    printf '%s\n' 'Requirement: "nmcli" not found in path.'
fi

case "${1}" in
    '--help'|'-h')
        twshowhelp
        exit 0
    ;;
    '--status')
        nmcli radio wifi | awk '{printf("%s: %s%s\n","Wifi Radio Is",toupper(substr($1,1,1)),substr($1,2))}'
        exit 0
    ;;
    '--exec')
        if [ "$(nmcli radio wifi)" = "enabled" ]; then
            printf 'Was: Enabled\nTurning Off\n'
            nmcli radio wifi off
        elif [ "$(nmcli radio wifi)" = "disabled" ]; then
            printf 'Was: Disabled\nTurning On\n'
            nmcli radio wifi on
        fi
        exit 0
    ;;
    *)
        printf '%s\n\n' 'No Action Specified.  Please refer to help below'
        twshowhelp
    ;;
esac

