#!/bin/sh
twshowhelp() {
    printf '%s\n%s\n%s\n%s\n' \
        'Toggles the state of the wifi radio.' \
        ' --exec       will perform the toggle' \
        ' --cycle      will turn wifi OFF, wait 2 sec, then back on' \
        ' --status     will show the current status and exit'
}

twexec() {
    if [ "${radioState}" = "enabled" ]; then
        printf 'Was: Enabled\nTurning Off\n'
        nmcli radio wifi off && radioState="disabled"
    elif [ "${radioState}" = "disabled" ]; then
        printf 'Was: Disabled\nTurning On\n'
        nmcli radio wifi on && radioState="enabled"
    fi
}

if ! command -v nmcli 1>/dev/null 2>&1; then
    printf '%s\n' 'Requirement: "nmcli" not found in path.'
else
    radioState="$(nmcli radio wifi)"
fi

case "${1}" in
    '--help'|'-h')
        twshowhelp
        exit 0
    ;;
    '--status')
        nmcli radio wifi | awk '{printf("%s: %s%s\n","Wifi Radio Is",toupper(substr($1,1,1)),substr($1,2))}'
        exit 0
    ;;
    '--exec')
        twexec
        exit 0
    ;;
    '--cycle')
        if [ "${radioState}" = "enabled" ]; then
            twexec
            sleep 2
            twexec
        else
            printf 'This switch is only supported when wifi is enabled.\n'
            exit 1
        fi
        exit 0  
    ;;
    *)
        printf '%s\n\n' 'No Action Specified.  Please refer to help below'
        twshowhelp
    ;;
esac

