#!/bin/sh
twshowhelp() {
    printf '%s\n%s\n%s\n%s\n%s\n%s\n' \
        'Toggles the state of the wifi radio.' \
        ' --on,  --enable         turn wifi state to on' \
        ' --off, --disable        turn wifi state to off' \
        ' --toggle                toggle current state' \
        ' --cycle                 turn wifi OFF, wait 2 sec, then back on' \
        ' --status                show the current status and exit'
}

twexec() {
    if [ "${radioState}" = "enabled" ]; then
        if [ ! "${1}" = "silent" ]; then
            printf 'Was: Enabled\nTurning Off\n'
        fi
        nmcli radio wifi off && radioState="disabled"
    elif [ "${radioState}" = "disabled" ]; then
        if [ ! "${1}" = "silent" ]; then
            printf 'Was: Disabled\nTurning On\n'
        fi
        nmcli radio wifi on && radioState="enabled"
    fi
}

if ! command -v nmcli 1>/dev/null 2>&1; then
    printf '%s\n' 'Requirement: "nmcli" not found in path.'
else
    radioState="$(nmcli radio wifi)"
fi

case "${1}" in
    '--help'|'-h')
        twshowhelp
        exit 0
    ;;
    '--on'|'--enable')
        printf 'Setting Wifi State Unconditionally To: On\n'
        nmcli radio wifi on
    ;;
    '--off'|'--disable')
        printf 'Setting Wifi State Unconditionally To: Off\n'
        nmcli radio wifi off
    ;;
    '--status')
        nmcli radio wifi | awk '{printf("%s: %s%s\n","Wifi Radio Is",toupper(substr($1,1,1)),substr($1,2))}'
        exit 0
    ;;
    '--toggle')
        twexec
        exit 0
    ;;
    '--cycle')
        if [ "${radioState}" = "enabled" ]; then
            printf 'Setting Wifi State To Off\n'
            twexec silent
            sleep 2
            printf 'Setting Wifi State To On\n'
            twexec silent
            sleep 2
            printf 'Wifi Cycling Complete\n'
        else
            printf 'This switch is only supported when wifi is enabled.\n'
            exit 1
        fi
        exit 0  
    ;;
    *)
        printf '%s\n\n' 'No Action Specified.  Please refer to help below'
        twshowhelp
    ;;
esac

